---
language: node_js
node_js:
  - "4.4.0"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-1-13
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - npm install yarn --global
  - yarn --version
  - npm install -g bower
  - "npm install -g npm@^2"
  - "npm install -g phantomjs-prebuilt"

install:
  - yarn
  - bower install

script:
  - npm test
  - ember try $EMBER_TRY_SCENARIO test
