---
language: node_js
node_js:
  - "4.4.0"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-1-13

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-1-13

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g phantomjs-prebuilt"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
  - ember try $EMBER_TRY_SCENARIO test
